### PR TITLE
Ajax options squashed nolan

### PR DESCRIPTION
**Pull request by nolanlawson**
Same as #8, but with tests and documentation.

### CODE REVIEW

**Comment by alanquigley** [comment]
Has the package built?

**Comment by alanquigley** [comment]
yes, just took a while. Thanks

**Comment by nolanlawson** [comment]
yep, just published as 1.3.0 :)

**Comment by robertkeizer** [comment]
@nolanlawson Thanks! I just hadn't found the time to get the tests done!

**Comment by nolanlawson** [comment]
no prob, we all have lives outside of this stuff. :)

**Pull request merged**
