### PR TITLE
Simple ajax options if defined.

### PR DESCRIPTION
**Pull request by robertkeizer**
I wanted to up the timeout and didn't have a way to modify the default ajax options per request.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Sweet! So this is failing the coverage tests; can you add a test that just adds a bogus param? Either that or just use 

```js
/* istanbul ignore:next */
```

**Comment by alanquigley** [comment]
Any plans to merge this?

**Comment by nolanlawson** [comment]
This is still failing the tests, but I can fix that.

**Comment by alanquigley** [comment]
Great!

**Comment by nolanlawson** [comment]
merged in https://github.com/nolanlawson/pouchdb-load/pull/9

**Pull request merged**
