### PR TITLE
(#11) - use up-to-date pouchdb-ajax

### LINKED ISSUE #11: Local files in iOS
For local files, you can just use the filename and path in the url but for iOS a modification must be done. 

line 188:
if ((xhr.status >= 200 && xhr.status < 300) || (xhr.status==0 && xhr.responseText.length>0) ) {

the additional or condition is because for some reason, iOS is returning 0 as the status for the xhr request even when there is data loaded from file. Maybe this is because file is not http but anyway now its working for Android, WP and iOS.

### PR DESCRIPTION
**Pull request by nolanlawson**
This ought to fix #11 because we're not using the old version of PouchDB's `ajax` anymore.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Related to https://github.com/pouchdb/pouchdb/pull/3559

**Comment by nolanlawson** [comment]
@vpease let me know if this fixes the issue for you

**Comment by nolanlawson** [comment]
released in 1.3.1

**Comment by nolanlawson** [comment]
ugh, forgot to build. released in 1.3.2

**Comment by vpease** [comment]
Tested on iOS
same status:500, name: unknown_error i used to have before doing the modification to line 188 in 1.3.0

**Pull request merged**
