### PR TITLE
Include query_params in replIdOpts

### PR DESCRIPTION
**Pull request by wegewerk-mdt**
Include query_params in replIdOpts. Without a useless Checkpointer ist created, leading to sync from seq=0 on next sync.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Ooh, I totally missed this. This will need a test in order to pass (due to code coverage), but yeah, this is a good fix.

**Comment by wegewerk-mdt** [comment]
I copied the Test '/w a filter' and adapted it for this case. Code coverage ist at 100% again, but i dont understand why the test itself fails.

**Comment by nolanlawson** [comment]
Hmm, Travis says the error is `quux never loaded, because its seq is 1`. Did you try to run your tests locally?

**Comment by wegewerk-mdt** [comment]
Yes i did. The tests 1) and 2) also do fail. They also fail without my patch.

**Comment by nolanlawson** [comment]
You're absolutely right; the build started breaking because of a change in PouchDB itself, which I could have avoided by implementing https://github.com/nolanlawson/pouchdb-load/issues/29. So I'll implement https://github.com/nolanlawson/pouchdb-load/issues/29 and then merge your PR.

**Comment by nolanlawson** [comment]
Merged as 56bfc4446dce293f0ac8fdc5d6fd0178c56327b3, thanks a lot!

**Pull request closed without merging**
